repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest version or a specific version
    hooks:
      - id: black
        language_version: python3.12.4  # Set this to the Python version you want everyone to use for formatting