# Name of the git hub action
name: Test GCE SSH Connection

# Trigger conditions
# on push or pull on branches, folders, files etc
on:
  push:
    branches:
      - aakash_dev

# Setting the environement for the GCP cloud engine that it is gonna talk to 
env:
  PROJECT_ID: ${{secrets.AIRFLOW_GCP_PROJECT_ID}}
  GCE_INSTANCE: airflow-instance
  GCE_INSTANCE_ZONE: us-central1-a

# Jobs that need to be performed 
jobs:
  # job definition
  test-ssh:
    runs-on: ubuntu-latest

    # Sub-processes or steps to run
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH access to the GCE VM using the SSH key from GitHub Secrets
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AIRFLOW_GCE_SSH_PRIVATE_KEY }}

      # Test SSH connection to the GCE VM
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AIRFLOW_VM_USERNAME }}@${{ secrets.AIRFLOW_VM_IP }} << EOF
            echo "Connected to GCE VM successfully!"
            hostname
            uptime
          EOF

