# Name of the git hub action
name: Airflow Server and Script Changes

# Trigger conditions
# on push or pull on branches, folders, files etc
on:
  push:
    branches:
      - aakash_dev
      # - rajat_dev
      # - amogha_dev
      # - jahnavi_dev
      # - nikhil_dev
      # - samanvya_dev
      # - dev
    paths:
      - 'dags/**'
      - 'airflow-config/docker-compose.yaml'

# Setting the environement for the GCP cloud engine that it is gonna talk to 
env:
  PROJECT_ID: ${{secrets.AIRFLOW_GCP_PROJECT_ID}}
  GCE_INSTANCE: airflow-instance
  GCE_INSTANCE_ZONE: us-central1-a
  PRIVATE_KEY: ${{secrets.AIRFLOW_GCE_SSH_PRIVATE_KEY}}

# Jobs that need to be performed 
jobs:

  add_ssh_key_job:
    runs-on: ubuntu-latest  
    steps:

      # Set up SSH access to the GCE VM using the SSH key from GitHub Secrets
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AIRFLOW_GCE_SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AIRFLOW_VM_USERNAME }}@${{ secrets.AIRFLOW_VM_IP }} << EOF
            echo "
            ############################################################
            "
            echo "Connected to GCE VM successfully!"
            hostname
            uptime
            echo "######################################################"
          EOF


  check_changed_directories:
    name: Check updated directories
    needs: add_ssh_key_job
    runs-on: ubuntu-latest
    outputs:
      dags_changed: ${{ steps.dags_changed.outputs.dags_changed }}
      airflow_config_changed: ${{ steps.airflow_config_changed.outputs.airflow_config_changed  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
  
      - name: dags directory changed
        id: dags_changed  # Step ID to reference output
        run: |
          echo "Checking if any files in the 'dags/' folder have changed..."
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^dags/'; then
            echo "'dags/' folder has changes."
            echo "::set-output name=dags_changed::true"
          else
            echo "'dags/' folder has no changes."
            echo "::set-output name=dags_changed::false"
          fi

      - name: airflow config directory changed
        id: airflow_config_changed
        run: |
          echo "Checking if any files in the 'dags/' folder have changed..."
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^airflow-config/'; then
            echo "'airflow-config/' folder has changes."
            echo "::set-output name=airflow_config_changed::true"
          else
            echo "'airflow-config/' folder has no changes."
            echo "::set-output name=airflow_config_changed::false"
          fi
      
      - name: debug changed files and directories output
        run: |
          echo "Changed directories: ${{ steps.dags_changed.outputs.dags_changed }}"
          echo "Changed files: ${{ steps.airflow_config_changed.outputs.airflow_config_changed }}"

  changed_files_and_folder_debug:
    runs-on: ubuntu-latest
    needs: 
      - check_changed_directories
    
    steps:
      - name: Debug changed directories output
        run: |
          echo "Changed directories: ${{ needs.check_changed_directories.outputs.dags_changed }}"
          echo "Changed files: ${{ needs.check_changed_directories.outputs.airflow_config_changed }}"

  # # job definition
  # airlfow_config_update:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - add_ssh_key_job
  #     - check_changed_files_and_directories
  #     - changed_files_and_folder_debug

  #   if: contains(needs.check_changed_files_and_directories.output.changed_files,'docker-compose.yaml')

  #   # Sub-processes or steps to run
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Cleanup all docker processes
  #       run: |
  #         ssh -o StrictHostKeyChecking=no ${{ secrets.AIRFLOW_VM_USERNAME }}@${{ secrets.AIRFLOW_VM_IP }} << EOF
  #           sudo docker compose down --volumes --rmi all
            
  #         EOF
  #     - name: Overwrite New docker-compose File
  #       run: |
  #         scp -o StrictHostKeyChecking=no /airflow-config/docker-compose.yaml ${{secrets.AIRFLOW_VM_USERNAME}}@${{secrets.AIRFLOW_VM_IP}}:/

  #         EOF
  #     - name: Docker Compose Up Commands
  #       run: |
  #         ssh -o StrictHostKeyChecking=no ${{ secrets.AIRFLOW_VM_USERNAME }}@${{ secrets.AIRFLOW_VM_IP }} << EOF
  #           sudo docker compose up airflow-init  # Initialize Airflow
  #           sudo docker compose up -d  # Start the containers in detached mode
  #         EOF

  airflow_dag_scirpts_update:
    runs-on : ubuntu-latest
    needs:
      - add_ssh_key_job
      - changed_files_and_folder_debug
      - check_changed_directories

    if: ${{needs.check_changed_directories.outputs.dags_changed == 'true'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Overwrite The Dag folder
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -r -o StrictHostKeyChecking=no -i private_key ./dags/src/ ${{secrets.AIRFLOW_VM_USERNAME}}@${{secrets.AIRFLOW_VM_IP}}:/dags
