name: Deploy Front End Application

on:
  push:
    branches: 
      # - main
      - aakash_dev
    paths:
      - 'backend/app.py'
      - 'backend/rag.py' # Trigger workflow when these files are changed

jobs:

  deploy_app:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Shell Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bash # Ensure Bash is installed
    
    - name: Install sshpass
      run: |
        sudo apt-get install -y sshpass

    - name: Setup Github, Docker, Python on VM
      run: |
        chmod +x setup-scripts/setup_vm.sh
        cd setup-scripts
        ./setup_vm.sh

    - name: Remove Old Containers, Images, Python Environments
      run: |
        chmod +x setup-scrips/remove.sh
        cd setup-scripts
        ./remove.sh

    - name: Run Deploy Script
      run: |
        chmod +x setup-scripts/deploy_app.sh
        cd setup-scripts
        ./deploy_app.sh
