name: Create dvc JSON File from Secrets

# Trigger the workflow manually
on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  create_json_file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Add SSH key to allow communication with the remote server
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AIRFLOW_GCE_SSH_PRIVATE_KEY }}

      # Step 3: Generate JSON File using secrets
      - name: Generate JSON File from Secrets
        run: |
          echo "Creating JSON file from secrets"
          cat <<EOT > mlops-437516-b9a69694c897.json
          {
            "type": "service_account",
            "project_id": "${{ secrets.PROJECT_ID }}",
            "private_key_id": "b9a69694c897e52628918aa8ea99072747b08278",
            "private_key": "${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}",
            "client_email": "${{ secrets.CLIENT_EMAIL }}",
            "client_id": "${{ secrets.CLIENT_ID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/${{ secrets.CLIENT_EMAIL }}",
            "universe_domain": "googleapis.com"
          }
          EOT

      # Step 4: Transfer the JSON file to the remote server
      - name: Transfer JSON File to Remote Server
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key ./mlops-437516-b9a69694c897.json ${{ secrets.AIRFLOW_VM_USERNAME }}@${{ secrets.AIRFLOW_VM_IP }}:/home/aakashmahesha

      # Step 5: Verify the JSON file exists on the remote server
      - name: Verify JSON File on Remote
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.AIRFLOW_VM_USERNAME }}@${{ secrets.AIRFLOW_VM_IP }} << EOF
            if [ -f /home/aakashmahesha/mlops-437516-b9a69694c897.json ]; then
              echo "JSON file created and transferred successfully."
            else
              echo "Failed to create or transfer the JSON file."
              exit 1
            fi
          EOF
