name: Trigger Airflow DAG on File Changes

on:
  push:
    paths:
      - 'model/scripts/config.json'
      - 'model/scripts/train.py'

jobs:
  trigger-airflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Setup Script
        run: |
          chmod +x ./setup.sh  # Ensure the script is executable
          ./setup.sh           # Run the setup script

      - name: Start Airflow with Docker
        run: |
          docker compose up -d  # Start Airflow containers defined in a docker-compose.yml file

      - name: Trigger Airflow DAG
        run: |
          docker exec -ti <airflow-webserver-container> airflow dags trigger model_train_evaluate

      - name: Clean Up
        run: |
          docker compose down  # Stop and remove Airflow containers
